### ISSUE TITLE
Bundle size incorrect

### ISSUE THREAD

**Issue by aaronjensen** [coinbase/rest-hooks#103]
Hi there, this is an interesting looking package, but I think your bundle size in the readme may be a little misleading.

Given that you have a few dependencies that other people may not have (like superagent and reselect, for example), the bundle size is actually quite a bit higher than advertised: : https://bundlephobia.com/result?p=rest-hooks@2.0.1

**Comment by ntucker** [comment]
Thanks for reporting this issue! Measuring bundle size is certainly difficult given the nature of how different people could possibly include a library. Because of this one simple number is indeed an oversimplification. Having said that, I think it's useful to have a number of what people can reasonably expect to grow their total bundle in a normal project. I'll lay out my reasoning and I encourage you to inject your own perspective on the subject.

The number we try to give should represent around what should be expected to add to a bundle. Of course this will vary based on a few factors. First off, normalizr is a key library that provides much of the functionality here. It is not a general purpose library - so it is 100% counted toward the bundle size. Note that both this and that library support tree-shaking. Rest Hooks in fact includes many optional features that would typically be considered mutually exclusive (like redux integration vs useReducer() based Provider). This means in the real world there will be many parts of the code that will not be included in the library. So really we're giving an upper bound on those things. To address bundlephobia - it claims 50% is from lodash. This is incredibly misleading as we only use lodash.merge and possibly one other tiny utility. Even build systems without tree shaking will not include the entirety of lodash. And given its popularity - it's even likely those modules were *already* included in someone's bundle. The same applies to babel/runtime as most people will be using babel with their code. This does break apart if they are targetting only modern browsers as runtime might include a few more pieces than they already used. Finally, the only library left to mention is superagent. Including superagent as a default was a conscious choice as we felt it provided the best experience - using the builder pattern and supporting SSR out of the box. However, you are free to use any other networking library that you might choose - or none at all. https://resthooks.io/docs/guides/custom-networking should lead you towards such a goal. In those cases your choice affects your bundle separately from Rest Hooks. Again, Rest Hooks supports tree shaking so you aren't required to use the superagent implementation. We do plan on making it easier to separate various pieces of Resource in the future so more tree shaking can be done. (For instance non-REST apis probably don't care to have the REST FetchShape generators.)

**Comment by aaronjensen** [comment]
Thanks for the thoughtful response. Here's a quick test using create-react-app. Not as bad as bundlephobia claims, but still a bit more of a jump than the readme. I hear you on tree-shaking and the complexity w/ providing a single number, so feel free to do whatever you like with this info and these thoughts. 

Before:

```
  36.44 KB  build/static/js/2.b41502e9.chunk.js
  762 B     build/static/js/runtime~main.a8a9905a.js
  602 B     build/static/js/main.28647029.chunk.js
  517 B     build/static/css/main.2cce8147.chunk.css
```

After:

```
  51.29 KB (+14.85 KB)  build/static/js/2.08fd04e9.chunk.js
  762 B                 build/static/js/runtime~main.a8a9905a.js
  735 B (+133 B)        build/static/js/main.5da66aa1.chunk.js
  517 B                 build/static/css/main.2cce8147.chunk.css
```

Here's the code I included:

```ts
import {useResource, useFetcher, Resource} from 'rest-hooks'

class Foo extends Resource {
}

useFetcher(Foo.updateShape())
useResource(Foo.detailShape())
```

Related: why is redux a dependency? It doesn't seem to be included, but I didn't look too closely.

**Comment by ntucker** [comment]
Redux is included for 'rest-hooks/testing'. I plan to move testing library to its own package (probably v3 as this is breaking change) but then I have to try getting my auto-release setup properly with lerna so working on other stuff for now.

The culprit for your measurement is superagent. So I made https://github.com/coinbase/rest-hooks/pull/113 to fix it. I've been meaning to do this since the beginning but getting generic types with inheritance working right was a bit of a hurdle. This PR allows people who want to use any networking library they choose - so this means that part of the bundle is up to them. Potentially if they only support modern browsers they could just use https://resthooks.io/docs/guides/custom-networking#fetch-https-developermozillaorg-en-us-docs-web-api-fetch_api and have 0 size impact.

I'm thinking of doing a blog post sometime in the future explaining bundle sizing in more detail (as in practice initial size is much lower in fact!). For now though I consider that PR to fix the issue as it truly makes the user's networking library of choice their own and thus should not be considered a part of the rest-hooks bundle impact.

**Comment by ntucker** [comment]
Taken from analyzing https://github.com/ntucker/anansi/tree/master/examples/typescript

![bundle](https://user-images.githubusercontent.com/866147/62000826-d1eb8680-b095-11e9-9a61-48d11af9e07e.PNG)

Sizes are split into three pieces:
entry: 2.54kb

resource: 1.21kb
superagent: 6.08kb

hooks: 1.86 + 0.468 = 2.33kb

**Total: 12.16kb**

And without superagent it becomes **6.08kb** total. Of course this is less than advertised size because the example doesn't use every single piece provided. For instance ExternalCacheProvider.

Note because this example has other things, the dependency on lodash.merge for instance was already there - which explains the slightly smaller results when including superagent.

**Comment by aaronjensen** [comment]
Sounds great, thanks!
