### ISSUE TITLE
How to get response object in rest-hooks

### ISSUE THREAD

**Issue by St1myL** [coinbase/rest-hooks#157]
I want to get the response object after POST using `useFetcher`

What we do with standard fetch:

```fetch(...).then(response => console.log(response)``` _// returns Response_

I want something like this but I get the body:

```post(...).then(response => console.log(response)``` _// returns Body_

------ 
<sub>sorry for my stupid questions:)</sub>

**Comment by ntucker** [comment]
I suspect there might be something more going on here. According to these lines:
https://github.com/coinbase/rest-hooks/blob/master/src/state/NetworkManager.ts#L76
and then
https://github.com/coinbase/rest-hooks/blob/master/src/state/NetworkManager.ts#L120

It should be resolving the promise with the response value.

If you could create a minimum reproducible codesandbox.io, or give more context I might be able to help uncover what's going on here.

**Comment by St1myL** [comment]
@ntucker 
<sub>Sorry, I've tried to create codesandbox for this issue, but it doesn't work. </sub>
I want to get Authorization header after POST
It's easier to show what I want to get (for example):
```
Response {
  body: (...)
  bodyUsed: false
  headers: Headers {}
  ok: true
  redirected: false
  status: 200
  statusText: ""
  type: "cors"
  url: "https://jsonplaceholder.typicode.com/todos/5"
}
```
I thought I could get the Response this way: 

```
post({some_data}, {}).then(response => console.log(response) // returns Body

{
  completed: false
  id: 5
  title: "laboriosam mollitia et..."
  userId: 1
}

```

**Comment by ntucker** [comment]
Ah, I see. I can tell you why that is happening, and how you can change that. I'm curious to know your use-case to see if maybe there are things that could change or at least documentation notes about this.

What is happening: the default fetch implementation in Resource is going to resolve to the body of the response, rather than the whole response object. You can see this here: https://github.com/coinbase/rest-hooks/blob/master/src/resource/Resource.ts#L30.

Why: Resolving to an object is defined by the [FetchShape](https://resthooks.io/docs/api/FetchShape#fetchparams-param-body-payload-promise-any) spec. This is needed to make the [networking library opaque so it can easily be changed](https://resthooks.io/docs/guides/custom-networking). After all, all Rest Hooks needs is an object - it doesn't care how it's retrieved.

How to resolve: Currently the recommended approach to using headers is [customizing the fetch function](https://resthooks.io/docs/guides/pagination#tokens-in-http-headers) so relevant headers are included in the data.

Considerations: If you only need it in your promise resolution but not actually stored in the cache this might be a bit odd (is that true?). Though in practice just putting extra data there isn't a big deal. Perhaps instead of just resolving to the body, we should define a standard shape that includes both body and headers if this is a common thing. Does this seem like a good idea to you?

```typescript
interface ResponseResolution {
  body: object,
  headers?: { [key: string]: any },
}
```

**Comment by St1myL** [comment]
@ntucker 

**Use-case:**
I have a passport service for authorization/registration. When user logs in I need to save Authorization token to localStorage. When this token expires (401), we do a double redirection and so on.

**About considerations:**
Yeah, I think it would be nice to include both. In my case, this may not be cached, because as soon as the user logs in, the passport redirects to the main service.

**Comment by ntucker** [comment]
In this case, my recommendation would be to deal with auth at the fetch (aka networking) layer. If you're using the default then it could easily be accomplished by adding a [superagent](https://visionmedia.github.io/superagent) [plugin](https://resthooks.io/docs/guides/auth). These are simply functions that take a request and expect it to be returned. Since superagent uses the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern), you can use that opportunity to modify the request or take header data about auth tokens and do with them what you will (by storing them in localstorage for instance).

**Comment by St1myL** [comment]
I apologize for the response so slow, yes, it helped me, thank you very much
