### ISSUE TITLE
Have there been issues using suspense with "Legacy Mode"?

### ISSUE THREAD

**Issue by bywo** [coinbase/rest-hooks#178]
Hey! This isn't a feature request or a bug report, just a question.

Reading React's [docs on Suspense for Data Fetching](https://reactjs.org/docs/concurrent-mode-suspense.html), it seems like suspense for data fetching is "experimental", and different than suspense for lazy code loading:

> React 16.6 added a `<Suspense>` component that lets you “wait” for some code to load and declaratively specify a loading state (like a spinner) while we’re waiting...Suspense for Data Fetching is a new feature that lets you also use `<Suspense>` to declaratively “wait” for anything else, including data.

The React docs also only show suspense for data fetching in conjunction with Concurrent Mode (i.e. `ReactDOM.createRoot(rootElement).render()` instead of `ReactDOM.render()`.

Since this library does suspense for data fetching, I'm wondering if you have any insight as to why the React team considers it experimental. Have you run into any bugs or race conditions during development of the library or in production usage? Do you use Concurrent Mode or Legacy Mode React?

Thanks!

**Comment by ntucker** [comment]
I have been tracking all of this very closely and talked to the core team several times. That said, this is my own observation and perspective on what I have observed, so take this all with a grain of salt.

That being said... I understand this to be a branding issue. The React team has been working on concurrent mode and suspense for years now and it's going to do amazing things. However, because they are providing a library they are afraid that people might build bad experiences and it would tarnish the brand of what is possible. Because of this they would like to keep a clear distinction between the 'old way' and 'full concurrent + suspense'. The future is quite bright, you can see some examples of what's possible here: https://codesandbox.io/s/concurrent-react-example-ly1ds. These types of next-level experiences are only possible when fully opting-in.

However, I believe that there is still benefit to using Suspense in legacy mode as it has greatly increased ergonomics around handling loading, error, happy paths.

Rest Hooks was built with both in mind. We use it at Coinbase in legacy mode and it was designed from the start to enable the next-level experiences that concurrent mode promises. In fact, because of many of the performance features of Rest Hooks, even in legacy mode it's providing many of the benefits of what the React core team describe as essential.

Our current plan at Coinbase is that we expect a non-experimental release of concurrent mode some time in the next few months. In that time we will attempt to make progress towards validating in Strict mode. Doing this enables us to enable Sync Mode, which will bring some additional benefits over legacy. The final goal is to get to concurrent mode, but since we are still migrating off mobx, this will take some time to achieve. (mobx and redux are inherently incompatible with concurrent mode.)

If we hadn't already started migrating this spring we would be waiting much longer to get on concurrent mode. This way we've benefited greatly from the new architecture while preparing soundly for the fun and amazing future that is Concurrent Mode.

**Comment by bywo** [comment]
Thank you for the thorough and helpful response!
