### ISSUE TITLE
Resource pk cannot be of type "number" as per the usage guide

### ISSUE THREAD

**Issue by jannisg** [coinbase/rest-hooks#258]
**React version**
`16.12.0`

**Concurrent mode** no

**Describe the bug**
Using version `4.3.1` of `react-hooks` in Webstorm, the types that come with the package fail when following the Getting Started usage example found [here](https://resthooks.io/docs/getting-started/usage).

The example demonstrates a Resource id as `number` which is then used and returned by the `pk` method.

In practice, the return value (according to the types at least) must be `string | undefined` hence `number` as per the example is not a supported use case.

**To Reproduce**
I think the above describes it adequately well, but if not let me know or simply try to return a `number` from `pk () { }` and see the error.

**Expected behavior**
- I expect the getting started example to work
- I would expect a `number` to be usable as a valid `pk` value

**Additional context**
<img width="701" alt="Screen Shot 2020-01-30 at 10 42 18 AM" src="https://user-images.githubusercontent.com/109211/73400274-b23b6080-434d-11ea-80cc-2045a3364baa.png">

**Comment by ntucker** [comment]
Ahh, wow didn't update the docs for this one. You can fix this simply by calling toString like so:

```typescript
pk() {
  return this.id?.toString();
}
```

This definitely should be updated in all the examples. Ultimately since this is used to index into Objects, it's effectively a string anyway, and we recently made that explicit as a type requirement to simplify some of the code paths. However, I'm curious to hear your thoughts on this and if this seems problematic other than simply not having correct documentation.

Looking forward to your thoughts on the matter!

**Comment by jannisg** [comment]
Thanks for the quick reply :)

I did some digging through the source code after creating the issue and found this suggestion implemented in one of the files as well, easy enough and personally I have no issues converting to keys either so I think just an update to the docs would be all that's required here.

Nice library by the way, just getting into it today but really enjoying the tidiness of the resource definition and then the calling from the React component 👍
