### ISSUE TITLE
Add action to manually update redux or context state

### ISSUE THREAD

**Issue by Jamakase** [coinbase/rest-hooks#283]
Currently, rest-hooks support updating only via requests. 

I understand that this project is intended to be used within react context, but it may be useful to have some port, that could help migrate from other codebases where store update is done via redux-saga or some other technology.

Also, this could be useful when some updated are received from websockets or other sources ( info is dehydrated from local storage).

I am currently using redux-actions with `RECEIVE_TYPE` but it feels a bit wrong to do it as it is internal API details.

**Comment by ntucker** [comment]
Using middlewares to dispatch actions is intended in https://resthooks.io/docs/guides/redux, as well as with custom [managers](https://resthooks.io/docs/api/Manager).

I do agree, the actions are not documented and seem like internal APIs. While they have been somewhat stable for the year of rest-hooks' existence so far - they have certainly changed. I do plan on cleaning up their API and locking down their interface along with providing more documentation around using them. When that happens, it will be clear what changes need to be made, but expect them to be minor. For instance my only current plan is to rename the 'url' member - since it's not very accurate description of its data anymore.

**Comment by ntucker** [comment]
'@rest-hooks/core' now exports createFetch(), createReceive() which construct actions to dispatch. Will be adding docs soon - see types for now.
