### ISSUE TITLE
Thoughts on Mocking all Resources

### ISSUE THREAD

**Issue by arabold** [coinbase/rest-hooks#285]
I've been using the `MockProvider` to mock responses to general `useResource(...)` requests. That works pretty well and I like the overall syntax. However, I needed a way of mocking not only cached data but all requests including `post`, `put`, etc. This way I can test easily complete workflows in Storybook. I considered using `fetch-mock` but that seemed to low level for my purpose. I wanted something that taps directly into `rest-hooks`.

Therefore I wrote a small hack for `rest-hooks` that allow me to customize all fetch requests. I'm posting it here to get some thoughts and feedback on this. Would that be a nice addition to `rest-hooks` or do you feel this goes down a wrong path?

```ts
// MockApiRequest.tsx
import { Method } from "rest-hooks";

export type MockApiRequest = {
  path: string | RegExp;
  method: Method | Method[] | "*";
  response?: any;
  responseCode: number;
  delay?: number;
};

const registeredMocks: MockApiRequest[] = [];

/** Register a new fixture for the Mock API */
export function register(apiRequest: MockApiRequest) {
  registeredMocks.push(apiRequest);
}
/** Unregister a fixture from the Mock API */
export function unregister(apiRequest: MockApiRequest) {
  const index = registeredMocks.findIndex((mock) => mock !== apiRequest);
  if (index >= 0) {
    registeredMocks.splice(index, 1);
  }
}
/** Test a given URL and method to match any of the registered fixtures */
export function matchRequest(method: Method, url: string) {
  return registeredMocks.find((mock) => {
    if (
      (typeof mock.method === "string" && (mock.method === method || mock.method === "*")) ||
      (Array.isArray(mock.method) && mock.method.includes(method))
    ) {
      // We match the method, check the URL
      if (typeof mock.path === "string") {
        const path = url.split("?")[0];
        const wildcard = mock.path.indexOf("*");
        if (wildcard >= 0) {
          return mock.path.substring(0, wildcard) === path.substring(0, wildcard);
        } else {
          return mock.path === path;
        }
      } else if (mock.path instanceof RegExp) {
        return mock.path.test(url);
      }
    }
    return false;
  });
}

export default {
  register,
  unregister,
  matchRequest,
};
```

The fixtures are injected with my own version of a `MockApiProvider`:
```tsx
// MockApiProvider.tsx
import React, { useEffect } from "react";

import { MockApiRequest, register, unregister } from "./MockApiRequest";

export interface MockApiProviderProps {
  fixtures: MockApiRequest[];
}

/** A very hacky way of mocking API responses. */
export default function MockApiProvider({ fixtures, children }: React.PropsWithChildren<MockApiProviderProps>) {
  useEffect(() => {
    fixtures.forEach((mock) => register(mock));
    return () => fixtures.forEach((mock) => unregister(mock));
  }, [fixtures]);
  return <>{children}</>;
}
```

And my custom `ApiResource` updates the `fetch` as follows:
```tsx
// ApiResource.tsx
// [...]
export default abstract class ApiResource extends SimpleResource {
// [...]
  /** Perform network request and resolve with json body */
  static async fetch(method: Method, url: string, body?: Readonly<object | string>) {
    // We hack a little bit of mock magic in here for easier testing
    const mockedResponse = matchRequest(method, url);
    if (mockedResponse) {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          if (mockedResponse.responseCode >= 200 && mockedResponse.responseCode <= 299) {
            resolve(mockedResponse.response);
          } else {
            reject(new ApiNetworkError("HTTP Request Error", mockedResponse.responseCode));
          }
        }, mockedResponse.delay ?? 0);
      });
    }
    return super.fetch(method, url, body);
  }
}
```
 
With this code I can finally mock everything. For example, here's my story to render a profile information about a user:

```tsx
export const profileFixtures: MockApiRequest[] = [
  {
    path: `${AccountResource.urlRoot}/me`,
    method: "get",
    responseCode: 200,
    response: {
      id: "testuser",
      avatarUrl: "https://i.pravatar.cc/300",
      firstName: "Johnny",
      lastName: "Tester",
    },
  },
  {
    path: "*",
    method: "*",
    responseCode: 500,
  }
];

storiesOf("Components / Profile", module)
  .add("Default", () => (
    <MockApiProvider
      fixtures={[
        {
          path: `${AccountResource.urlRoot}/lastLogin`,
          method: "get",
          responseCode: 200,
          response: {
            time: "2020-01-17T11:05:57Z",
          },
        },
        ...profileFixtures,
      ]}
    >
      <Profile />
    </MockApiProvider>
  ))
  .add("No Previous Login", () => (
    <MockApiProvider
      fixtures={[
        {
          path: `${AccountResource.urlRoot}/lastLogin`,
          method: "get",
          responseCode: 404,
        },
        ...profileFixtures,
      ]}
    >
      <Profile />
    </MockApiProvider>
  ));
```

Overall I'm actually quite happy with the result and see some power in this concept.  Happy to hear your thoughts and discuss!

**Comment by resolritter** [comment]
One thought on this is that the `registeredMocks` should be per-provider instead of one shared object for the whole tree.

Although I don't think your `MockProvider` configuration is necessary at all for achieving this. You could simply do with constants, which don't even need the setup/teardown effect you're doing there and are more flexible in general.

My idea would be to map each subtree to an id:

```javascript
const mockedEndpoints = {
   someTreeId: function (method, url, body) {
      if match(method, url, body) {
      // ...
      }
   },
   anotherTreeId: function (method, url, body) {
      if match(method, url, body) {
      // ...
      }
   }
}

function mockedEndpointsMatcher(method, url, body) {
// match on mockedEndpoints
}
```

where you provide the each subtree's id through a context

```javascript
<MockIdContext.Provider value={someTreeId}>
{ your component tree here }
</MockIdContext.Provider/>
```

then inside of the tree, consume that context

```javascript
const mockId = useContext(MockIdContext)
const resource = useResource(
    SomeResource.listShape(),
    { ...params, mockId },
  )
```

then you'd simply have to see if `mockId` is provided in the request's body or URL. If it is, you forward to some `mockedEndpointsMatcher`. 

This approach would allow you to mock dynamically at runtime. For instance, you could update the `MockIdContext` value to become "ALWAYS_FAIL" after three seconds through some effect, which would cause all effects only in that subtree to fail. Or you could have the context's value be an array of ids instead of a single id, which stops at the first id which is matched, for a fallback pattern.

**Comment by ntucker** [comment]
Thanks for the thoughtfulness put into this. I'm curious about all that extra response code and method stuff and what use cases its necessary for. I'm not sure I understand the subtree concept. If each story is a distinct tree, what is the purpose of subtrees for different cases? It might be easier for me to follow the concepts presented here with fleshed out examples of usage (rather than implementation details).

I imagine at least for the use cases I have in mind, simply expanding the same interface of MockProvider to also handle mutates could work. In this case we make the interface about how it should process a given request and return the response - similar to how network mocking libraries like `nock` work:

```tsx
// one entry per endpoint
[
[
MyResource.create(),
(params, body) => ({ id: uuid.uuid4(), ...body }),
],
[
OtherResource.detail(),
({ id }) => ({ id, title: 'best entry', name: 'bob' }),
],
]
```

In this case we can also support simple static mocks by putting their static definition as the return value.

Some additional considerations would be since it's actually waiting to resolve, should we setup suspense boundaries? What about if we want to fake a network error? Maybe just throw an error in the function. What if there's a sequence of fetches to the same endpoint with the same params and it should be different each time? Could be done with a closure tracking how many times the function has been called. This would be a bit verbose but still easily supported by the api.

### Implementation

In this case, instead of priming the cache with values, it would act as a Manager that intercepts requests and fulfills them.

Perhaps we could even have extra arguments for options like fake response timing so you can simulate loading state.

```tsx
[
MyResource.create(),
(params, body) => ({ id: uuid.uuid4(), ...body }),
{ delay: 500 }
]
```

### Thoughts?

Would love to hear more details about your use cases and also what everyone thinks of this concept!

**Comment by ntucker** [comment]
https://resthooks.io/docs/api/MockResolver (new in @rest-hooks/test v2) solves
- mocking anything (not just GET)
- application to particular subtrees instead of global

Closing this since it works!
