### ISSUE TITLE
@types/react as dependency

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#31]
Is it necessary to specify react types as a dependency or would it be sufficient to have it as a devDependency?

The reason for this issue is that having a dependency on the react types (in particular a specific version of it) is likely to at some point cause users to get multiple versions of the react types installed, which usually causes type errors that are difficult to debug.

Alternatively it could be a wildcard version, which is how dependencies between @types packages are speceified:
```json
"@types/react": "*"
```

(I currently have to use yarn resolutions to force an older version of the @types/react while I wait for [this issue](https://github.com/mui-org/material-ui/issues/15157) in material-ui to be resolved)

**Comment by ntucker** [comment]
Which version are you setting it to?

**Comment by ntucker** [comment]
Looks like that issue was fixed in material-ui. I don't see how this library could work with 16.7 types as it makes use of explicit 16.8 features in the type definitions. React.Dispatch, React.Reducer, etc.

**Comment by ntucker** [comment]
It probably makes sense to make @types/react a peerdep, but then I'd sort of be forcing people to use typescript. I guess if it's optionalpeerdep if they don't have it and are using typescript they're already doing that part wrong.

**Comment by ntucker** [comment]
Can you see if 1.1.2-beta.3 works for you?

**Comment by skoging** [comment]
I can confirm this resolves the issue for me.

Just to be clear, the main issue was that `@types/react@16.8.9` narrowed the type of the `ButtonHTMLAttributes.type` to `type?: "submit" | "reset" | "button";` which broke material-ui since they extended this with `type?: string;`.

This was however not what initially broke my build. That was casued by updating rest-hooks resulting in duplicate versions of @types/react to be installed. This sent me down a rabbit hole updating material-ui and various @types/* packages to try to resolve the type issues, before I realized that rest-hooks was the only package i used that depended on a specific version of @types/react.

This is not something specific to rest-hooks. I've had plenty of similar issues before with @types/* packages.

The solution using optional peer dependencies seems to solve all of these issues, but is apparently only implemented in yarn. This isn't an issue for me, but anyone not using yarn (and not typescript) will now get a warning about missing peer dependency that they don't need. (@types/* packages internally use wildcard version dependencies to avoid duplicate versions)

I don't really think there is a solution that solves this in a good way, but it seems common to avoid having @types/* dependencies, at least for peer dependencies like react.

**Comment by ntucker** [comment]
Sadly I don't there really is a perfect solution here. The only way to truly guarantee the same package is used in a library and its consumer is with peerdeps. Since I'm already putting react as a peerdep it sort of makes sense to make its types the same.

Having more flexible matching will usually help make it more likely to share a version, but often doesn't actually happen especially when packages are added over time. I could have simply made the dependency more loose like I did (^16.8.2) and it might have resulted in the same version in some cases. But the problems you had would still often occur otherwise.

Peerdeps specifications enable restrictions particular versions - and warning if they don't match. rest-hooks won't work with older versions of react, so it would be improper to allow them as weirder error messages would result. Similarly if react is a particular version its types must be.

As you correctly pointed out, npm does not currently support the functionality of optional peerdeps. However, that feature is fully backwards compatible so it fallsback to a normal peerdep. That means in the worst case (user using npm + no typescript) they will simply get a warning about the dependency. However, it won't actually block them. No  confusing bugs will occur. I feel like this is the best case, especially since this will hopefully be supported by npm in the future, and use of yarn is already widespread and encouraged in the docs I wrote.
