### ISSUE TITLE
List ressource handling

### ISSUE THREAD

**Issue by LentnerStefan** [coinbase/rest-hooks#32]
Hi,

This is a more a question rather than an issue. 

In my App, we display a list of comments ( about a user ) as well as a component allowing you to submit your own comment.

The comment resource is almost identical to the one in your [stackblitz example](https://stackblitz.com/edit/rest-hooks-cxa9uf?file=resources%2FCommentResource.ts).

In the List component I use : `useResource(CommentResource.listRequest(), { id });`
In the AddComment component i use : ` useFetcher(CommentResource.createRequest());`

However when I add the comment, the ListComponent does not rerender with the added comment.
I can see the new Comment  is added to the `entities` of the state context, but not in the `results`.

![Screen Shot 2019-04-03 at 14 12 31](https://user-images.githubusercontent.com/18282455/55477895-8d396c80-561a-11e9-869e-abc8eba103cc.png)

What is your recommended way of handling this kind of behaviour ? Should i refetch the Comments List entirely after posting? Is there something I'm missing ? 

Thank you :)

**Comment by ntucker** [comment]
The plan is to allow you to specify requests you want to insert the response into like the list request you mentioned. However the interface for this isn't 100% obvious so I hadn't built it yet. For now refetching would probably be the best workaround but rest assured this will be fixed soon

**Comment by LentnerStefan** [comment]
Okay! Thank you :)

**Comment by cif** [comment]
I'm super new to this library which I'm really enjoying so far. What's the preferred method for performing a manual refetch you're referring to?  

Simply calling the static fetch method on resource before the listRequest doesn't seem to do the trick for me

```
OrganizationResource.fetch('get', 'http://localhost:3000/organizations/');
const orgs = useResource(OrganizationResource.listRequest(), {});
```

**Comment by ntucker** [comment]
https://resthooks.io/docs/api/useFetcher should work. It returns a function and that function will always issue the call even if the cache is considered valid - so no need for useInvalidator() if you call that function yourself.

The difference with `OrganizationResource.fetch` is that the method just mentioned only does the fetch - but it doesn't update the cache. The function returned by useFetcher() will update the cache, and thus update the resource you are using with useResource().

**Comment by cif** [comment]
Thanks for quick response!

The function returned by useFetcher is a promise so, as I understand it, in order to throw that promise and make use of suspense like useResource does (which is awesome btw), I'd have to replicate some kind of caching functionality to avoid re-throwing on render? 

I think `useInvalidator` is a fine solution that seems in line with suspense patterns https://medium.com/@Charles_Stover/react-suspense-with-the-fetch-api-a1b7369b0469. The terminology "refetch" had me looking for a specific method to call  

As you state above, it might be nice to directly update the cache after requests as desired. I'm starting to get more familiar with the library source, hope to contribute in the future

**Comment by ntucker** [comment]
@cif glad you figured it out tho TBH I'm not sure I completely understand your use case. invalidation definitely allows new fetch triggers to happen so I guess that's all you needed. Don't hesitate to open new issues with any use cases!
