### ISSUE TITLE
Incorrect output from useResource() when overriding schema in listShape

### ISSUE THREAD

**Issue by michael-swarm** [coinbase/rest-hooks#423]
**React version** 16.13.1

**Concurrent mode** no

**Describe the bug**
I am using rest-hooks 4.5.9. I am working with an API that wraps a list in an object, just like [this example in the documentation](https://resthooks.io/docs/guides/endpoints#example-schema). That is, for the list URL, I get something like:
```
{ data: [item1, item2, ...] }
```
I followed the instructions in the documentation and overrode the `schema` in the `listUrl` in my resource class, let's call it `ItemResource`. I would now expect `useResource(ItemResource.listShape(), {})` to return an `ItemResource[]`. The TypeScript typings seem to agree with me. However, what it actually returns is `{ data: ItemResource[] }`.

**To Reproduce**
1. Create a subclass of `Resource` that overrides `listShape()`, overwriting the `schema` property with `{ data: [this.asSchema()] }`, as show in [the documentation](https://resthooks.io/docs/guides/endpoints#resource-definition).
2. Try to use this resource to fetch data from an API (or mocked API) that returns data in the corresponding format.

**Expected behavior**
`useResource()` should always return an array of the resource regardless of how the `schema` is defined.

**Additional context**
Great library, big fan!

**Comment by ntucker** [comment]
Thanks for the detailed report. Let's see if we can figure this out.

### Designed behavior

First, let's talk about the expected behavior (from library design). For https://resthooks.io/docs/guides/endpoints#example-schema example with `{ data: this.asSchema() }`, the expected return value from useResource() should be `{ data: ItemResource[] }`. So usage would be like:

```typescript
const { data: Items } = useResource(ItemResource.listShape(), {});
```

The idea is that the return value always matches (by default) whatever is returned from the API fetch. The schema definition is used to [normalize the cache](https://resthooks.io/docs/next/guides/debugging#normalized-cache), which enables consistency guarantees and performance improvements.

### TypeScript

Now given that, the fact that the types are listed as ItemResource[] instead of the data is definitely inconsistent at the very least, but also consistent with the expected behavior. To track this down, can you provide the exact Resource definition including the listShape() method?

### Getting the desired behavior

Rest Hooks is designed to be as opinionated about the API design and protocol as possible. Because of this, out of the box it does not try to assume anything even if it makes it more convenient. For this reason, (by default) it simply returns the same shape of the api. For cases like this, it can be very useful as access other items like [pagination tokens](https://resthooks.io/docs/guides/pagination) become much easier.

However, writing { data } = each time can be cumbersome, so there should be a way to customize it to get what you want.

One way would be to rewrite the API response itself so it simply uses the same form. This can be done by customizing the fetch function in the FetchShape - like done in [the examples](https://resthooks.io/docs/guides/network-transform#case-of-the-missing-id). Then your schema, can reflect that design. Here's how that might look:

```typescript
class ItemResource extends Resource{
  readonly something: string = '';

  pk() {
    return this.something;
  }

  static listShape<T extends typeof Resource>(
    this: T,
  ) {
    const superShape = super.listShape();
    return {
      ...superShape,
      fetch: async (params: {}, body?: Readonly<object | string>) => {
        const response = await superShape.fetch(params, body);
        return response.data;
      },
     schema: [this.asSchema()],
    };
  }
}
```

If your API follows this pattern commonly, you can easily just put this in a base class and then any classes that extend it will use the same behavior.

### Another alternative

Alternatively, you could build upon https://github.com/coinbase/rest-hooks/blob/3-maintenance/src/state/selectors/useSchemaSelect.ts the old design that would 'dive in' to find the first [Entity](https://resthooks.io/docs/api/Entity) defined in the schema. This is convenient to flexibly work with different schemas, however it adds several limitations to the types of APIs can be supported. Specifically

- It assumes there is always an entity in the response - so simply API shapes won't be supported
- It assumes there is only ONE top level entity (this can be a problem for including multiple related responses in a 'flat' layout)
- It assumes the only relevant data to look at is the entity (which is where cases like pagination break down).

**Comment by michael-swarm** [comment]
Wow, thank you for the detailed explanation! I now see the problem (in my code), which is actually just TypeScript-related.

I'm using [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint), which includes two [recommended](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) [rules](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md) that expect the overridden `listShape()` to have an explicit return type. So I copy-pasted the return type from the super class (`ReadShape<SchemaList<Readonly<AbstractInstanceType<T>>>>`). But now I see that, of course, is the equivalent of `ItemResource[]`. When I remove the return type (and ignore the eslint errors), everything is as you described. Now that you've explained it, this seems like a sensible way to handle things.

Figuring out the correct return types is actually something I've struggled with in general when overriding `Resource` methods. Perhaps I should just disable these eslint rules in my resource classes. But some docs on the matter would be helpful!

I'd be happy to review any documentation updates! What I think would be helpful for me:
- In that example, explicitly mentioning what `useResource()` will return in this case. I see now that it's clear from the normalizr documentation, but it took me a bit of digging to find that.
- Adding return types to overridden methods in the TypeScript examples (maybe this is just me, though)
- Perhaps some additional documentation on the TypeScript types and how to use them when overriding methods in subclasses

Thanks again for the awesome library and the detailed explanation!
