### ISSUE TITLE
Denormalization fails if nested entity lists are intended to be optional

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#637]
**React version**
17.0.1

**Concurrent mode** no

**Rest Hooks version** (e.g., 4.5.9)
rest-hooks: 5.0.9
@rest-hooks/rest: 1.0.4

**Describe the bug**
I'm trying to set up a resource with a nested list of entities that is intended to be optional.
```ts
export class SomeResource extends Resource {
  id: string = "";
  things: Nested[] = [];

  pk() {
    return this.id;
  }

  static schema = {
    things: [Nested]
  };

  static urlRoot = "/some";
}
```

Responses where `things` is not defined are normalized as expected, when inspecting the state with redux devtools everything is as expected. The default value is set:

Response:
```json
[
  {
    "id": "1",
    "name": "fails"
  },
  {
    "id": "2",
    "name": "works",
    "things": [
      {
        "id": "1",
        "name": "first"
      },
      {
        "id": "2",
        "name": "second"
      }
    ]
  }
]
```

State: 
```ts
{
  entities: {
    Nested: {
      '1': {
        id: '1',
        name: 'first'
      },
      '2': {
        id: '2',
        name: 'second'
      }
    },
    '/some': {
      '1': {
        id: '1',
        name: 'fails',
        things: []
      },
      '2': {
        id: '2',
        name: 'works',
        things: [
          1,
          2
        ]
      }
    }
  },
  results: {
    'GET /some': [
      '1',
      '2'
    ]
  }
}
```

When denormalized the first entity is missing: 

```ts

const list = useResource(SomeResource.list(), {});
// [{ id: '2', name: 'works', things: [...] }]

const fails = useCache(SomeResource.detail(), { id: '1' });
// undefined

```

**To Reproduce**
https://codesandbox.io/s/nostalgic-jepsen-17i64?file=/src/Resource.tsx

**Expected behavior**
Resource should be denormalized with the default value:

```ts

const list = useResource(SomeResource.list(), {});
// [{ id: '1', name: 'fails', things: [] }, { id: '2', name: 'works', things: [...] }]

const fails = useCache(SomeResource.detail(), { id: '1' });
// { id: '1', name: 'fails', things: [] }

```

**Additional context**
No automatic schema validation warnings are triggered. I would expect denormalization to work even if it did or if it was silenced.

**Comment by ntucker** [comment]
Currently the only way to mark members as optional is to set their default to `null`: https://resthooks.io/docs/api/SimpleRecord#optional-members

If you want to not always send a field, but for it to always exist - you can change the `fromJS()` method to add an empty list fallback.

```ts
export class SomeResource extends Resource {
  id: string = "";
  things: Nested[] = [];

  pk() {
    return this.id;
  }

  static schema = {
    things: [Nested]
  };

  static urlRoot = "/some";

  static fromJS<T extends typeof SimpleRecord>(this: T, props: Partial<AbstractInstanceType<T>>) {
    if (!Object.prototype.hasOwnProperty.apply(props, 'things')) props.things = [];
    return super.fromJS(props);
  }
}
```

**Comment by ntucker** [comment]
Would love to hear proposals of alternative ways this might be specified

**Comment by skoging** [comment]
I think it's unfortunate that default values cannot be used as they're intended in TypeScript. This workaround for specifying optional values is quite clunky and unintuitive.

I'd expect the required/optional relationship to be the reverse, as it is it would be in function arguments. My intention when setting default value is to ensure there always is a value when the input is optional. 

Intuitively, required properties would be those without undefined/null as part of the type, but no default value. I do understand this causes issues with readonly in TypeScript and would be harder to validate automatically, but I still don't agree with reversing the intuitive semantics of default values.

**Comment by skoging** [comment]
> We're piggybacking on the defaults here to try to define required/optional. If we really want to relax how that works we'd need some alternative way of marking things optional or required.

Is this only used for the automatic validation of response shapes?

**Comment by ntucker** [comment]
One of the core principals of Rest Hooks is that the server is the source of truth.

Because of this, the default use case is simply reflecting what the server sent - and being able to distinguish between server sending and not sending something is a legit use case (you might want to execute different code if something is not provided). Given that, Entity defaults are provided to ensure the expectations of the server API are always fulfilled - and thus conditionals that are not necessary can be eliminated (because they are typed to always be there), and creating fixtures becomes simple as well (SomeResource.fromJS({}) and you have a legit object).

However, sometimes users don't have control over their server API and really want to change things - which is the reason for many parts of https://resthooks.io/docs/guides/network-transform - but also why you can do the fromJS() override I suggested.

More importantly this begs the question - *if you want an empty list in the fallback case - why not just send an empty list from the server?* This would help me better understand the use cases to help with design.

"Intuitively, required properties would be those without undefined/null as part of the type, but no default value." I do agree it would be ideal to be able to extract the information from types alone - without some complicated babel plugin this isn't really doable, which is why I sort of fall back on the default types. Again - if you have ideas for semantically how to express both things, I would love to hear them. Perhaps the concepts of 'required' should be more cumbersomely expressed to make it easier for people to get started (loose by default, strict by opt-in). In that case, would still need some concept to express this.

> Is this only used for the automatic validation of response shapes?

Required is also used for determining if an entity deletion should cause a request to be considered invalid (and thus suspend). https://resthooks.io/docs/api/Delete However, the most common case is just for automatic validation.

I do agree that automatic validation should lean towards some false positives with no false negatives.

**Comment by ntucker** [comment]
If we make optional the default, and special syntax for required the most obvious way might be:

```typescript
export class SomeResource extends Resource {
  id: string = "";
  things: Nested[] = [];
  requiredThings: Nested[] = [];

  pk() {
    return this.id;
  }

  static schema = {
    things: [Nested],
    requiredThings: [Nested],
  };

  static required = ['requiredThings'];

  static urlRoot = "/some";
}
```

But then we have difficulty making sure only things in the required member are actually members.

More ideally if javascript supported proper metaprogramming we could use field definitions like the classic ORM concept:

```typescript
export class SomeResource extends Resource {
  id = StringField()
  things = [Nested]
  requiredThings = Required([Nested])

  pk() {
    return this.id;
  }

  static urlRoot = "/some";
}
```

**Comment by ntucker** [comment]
Just had another thought - if we overload the use of schema we can add aribtrary concepts to it.

```
export class SomeResource extends Resource {
  id: string = "";
  things: Nested[] = [];
  requiredThings: Nested[] = [];
  requiredPrimitive: number = 0;

  pk() {
    return this.id;
  }

  static schema = {
    things: [Nested],
    requiredThings: new schema.Array(Nested, { required: true }),
    requiredPrimitive: new schema.Required(0),
  };

  static urlRoot = "/some";
}
```

**Comment by ntucker** [comment]
@skoging Can you validate with the latest beta: 5.0.17-beta.0? Want to make sure it works as intended before I launch more broadly.

**Comment by skoging** [comment]
Will do 👍

**Comment by skoging** [comment]
I can confirm that this works as expected.

There are some resources with lots of optional properties (declared as `prop?: string;` for instance) without  a default value that cause validation errors when a certain number of them are present in the response, since they are considered "unexpected". Do these have to be declared with a `null` default to work? In any case I can easily get around that by disabling automatic validation.

**Comment by ntucker** [comment]
Hmmm....you could also make the default 'undefined'. Unless we add a compiler component, there's no way for the runtime to know a prop was declared. Though that might be an interested project. Eventually [class static block](https://babeljs.io/docs/en/babel-plugin-proposal-class-static-block) can help with some of this. Disabling can certainly cover these cases. The reason this exists is because it became obvious many people mis-create their schemas and end up getting a structure not like what they expected. Perhaps this will be less of an issue with the debugging tools and soon-to-be-released playground. Always open to new ideas of handling. Currently passing array to object, or response of html (because a soft 404), are separately parseable. The case of object and object is usually because it's nested. For instance { data: { myaactual: object }}. And they don't put the { data: Entity } in their schema. Always open to new ideas!

**Comment by skoging** [comment]
I figured that was the case, and it does make sense.

**Comment by skoging** [comment]
@ntucker Any chance this could be released soon?

**Comment by ntucker** [comment]
Just released new versions. Would have done last night but my internet died just before going to sleep.
