### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by blanchg** [coinbase/rest-hooks#85]
**React version** (e.g., 16.8.5) 16.8.6

**Concurrent mode** no

**Describe the bug**
Example storybook doesn't work as intended.

I get this error:
> Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    in ArticleList (at articlelist.stories.js:11)
    in MockProvider (at articlelist.stories.js:9)

If I add a suspense component then it get stuck at loading

    <MockProvider results={options.loading}>
        <Suspense fallback={"loading"}>
            <ArticleList maxResults={10} />
        </Suspense>
    </MockProvider>`

**To Reproduce**
Small repo displaying the error:
https://transfernow.net/231vh0a9o5d1

**Expected behavior**
Working test :)

**Comment by ntucker** [comment]
Found the problem. When you import 'rest-hooks/test' it imports the commonjs version (because it's expected to be able to run in node). However, in storybook it uses the normal module'd version that is built by webpack. This means the react `context` that is used in mockprovider is different from the one consuming in usecache(). So it's not passing the state because they are different contexts.

Really I should just make it a separate package...but I'll see if I can come up with an easier solution for now.

**Comment by ntucker** [comment]
Workaround:

Import from rest-hooks/lib/test
```typescript
import { MockProvider } from 'rest-hooks/lib/test';
```

Also - another bug is one of the mock test functions needs redux. So

```yarn add redux```

This will work until I figure out a real fix.

**Comment by ntucker** [comment]
Released https://github.com/coinbase/rest-hooks/releases/tag/1.6.7
