### ISSUE TITLE
List vs Detail Resource Issue (V5 upgrade)

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#876]
**React version** 16.13.1

**Concurrent mode** no

**Rest Hooks version** 5.1.1
**@rest-hooks/rest** 2.1.2,

**Describe the bug**
Most rest APIs have the strategy of showing limited attributes per item for List page while showing detailed attributes with associations for the Details page, e.g

/posts
```js
[
    { id: 1, title: 'Title 1' },
    { id: 2, title: 'Title 2' },
    ...
]
```

/posts/1
```js
{
    id: 1, title: 'Title 1', body: 'Body', user: {}, comments: [], ...
}
```
So, a separate request must be sent when viewing the detail page. This was the case for v4 but since the v5 upgrade, detail request is not being sent.

**To Reproduce**
https://codesandbox.io/s/reverent-mclaren-7r9ys

If you click 'View' for each post, a separate request for /posts/:id is not sent.

**Comment by ntucker** [comment]
Thanks for the report! I have some ideas and would love your input.

### Context

In Rest Hooks 5, we started tracking entity expiry data (in `entityMeta` part of state), which enabled us to apply the TTL policies on a per entity basis. This means when entities are already found - like in the case of going from a list to detail page, we could avoid an extra fetch call. While avoiding the fetch is not desirable if an incomplete entity is there, it is in any other case. This is especially useful as it allows useResource() usage even on pages where a detail item is nested within a list result. (Although that specific case can likely be detected some other way when concurrent mode is widespread, but that's a topic for another time.)

### Properties

- customizable behavior
- good out of the box detection
  - missing fields means fetch
  - all fields found means don't fetch
- high performance

### Solution 1

Customizable per-entity TTL

Add `static expiresAt(entityInstance, date)`. By default if expected fields are missing will return current date, otherwise add some TTL time.

### Solution 2

Mechanism for specifying required/expected fields for a given schema.

```ts
static list() {
  // we only expected id and title to come from this request
  return super.list().extend({ schema: [this.only('id', 'title')] });
}
```

**Comment by uxxman** [comment]
Thank you for the response.

From what I understand so far, I think the solution of specifying/checking missing/found fields will be a bit cumbersome, especially if the list is long or when we frequently add/remove fields from the underlying Resource definition.


### Solution 3

How about having a config **incomplete** which is false by default so everything keep working like it is currently and we can set it to true for endpoints which return limited attributes .i.e List pages

```js
static list() {
  return super.list().extend({ incomplete: true });
}
```

Then entities fetched via this method will all have **incomplete** set to false. This way the entity TTL can make use of this value to decide whether to fetch or not when a detail request is made and the detail request after completion will set the **incomplete** flag to false.

**Comment by ntucker** [comment]
I'm wary tying this to endpoints, since it has to do with now normalization works. Based on your design, what do you think about:

```ts
static list() {
  return super.list().extend({ schema: [this.partial())] });
}
```

**Comment by uxxman** [comment]
```js
static list() {
  return super.list().extend({ schema: [this.partial())] });
}
```

This would be ideal if this can ensure that the next detail request will make the api call, i.e.

```js
const post = useResource(PostResource.detail(), { id: postId });
```

**Comment by ntucker** [comment]
Working on something. ETA is a week from now. No promises tho.

**Comment by uxxman** [comment]
Much appreciated 👍🏻

**Comment by ntucker** [comment]
## Updates here:

Disabling results inferencing altogether: Simply override your Entity/Resource's static infer method to return undefined.

This is the provided implementation that does the previous behavior

```ts
  static infer(args, indexes, infer): any {
    if (!args[0]) return undefined as any;
    const id = this.pk(args[0], undefined, '');
    // Was able to infer the entity's primary key from params
    if (id !== undefined && id !== '') return id as any;
    // now attempt lookup in indexes
    const indexName = indexFromParams(args[0], this.indexes);
    if (indexName && indexes[this.key]) {
      // 'as Record<string, any>': indexName can only be found if params is a string key'd object
      return indexes[this.key][indexName][
        (args[0] as Record<string, any>)[indexName]
      ] as any;
    }
    return undefined as any;
  }
```

You'll need the latest release 5.2 for this.

This won't be exactly what you want - which is stale-while-revalidate. If you disable this it will just revalidate but not show stale data.

The next step is figuring out a good way for customizing the refresh policy - which is controlled by expiry time computations.

That currently is still in useDenormalized and looks like this:

```ts
    // TODO: move this to the .infer() method
    // oldest entity dictates age
    let expiresAt = Infinity;
    if (ready) {
      // using Object.keys ensures we don't hit `toString` type members
      Object.keys(resolvedEntities).forEach(key =>
        Object.keys(resolvedEntities[key]).forEach(pk => {
          expiresAt = Math.min(expiresAt, entityMeta[key][pk].expiresAt);
        }),
      );
    } else {
      expiresAt = 0;
    }
```

I'm wary of introducing something I'll need to support - already have a bunch of legacy stuff. I'm pretty confident with the infer part, but I was waffling around with the expiry time computation. It wasn't as clearly clean.

**Comment by uxxman** [comment]
@ntucker sorry couldn't check it our before. Just saw the PR 920, the solution looks interesting. Will give it try this week. Thank you again for the awesome work 😍

**Comment by ntucker** [comment]
New recommended way of doing this is using [validate](https://resthooks.io/rest/api/Entity#validate) - as explained in [summary list endpoints](https://resthooks.io/rest/guides/summary-list)

The key advantage here is this validate() failure results in *invalid* rather than *stale* flag. This is critical so components don't temporarily show summary data, which means you need conditionals in your code that don't correctly match the typescript.
